### ISSUE TITLE
Submit to sindresorhus/awesome?

### ISSUE THREAD

**Issue by RichardLitt** [chbrown/awesome-annotation#1]
Hey @chbrown; this is a good list. I had something similar at github.com/RichardLitt/awesome-annotation, and I submitted it to sindresorhus/awesome with the idea of getting more people to it. However, my list isn't great; certainly not as full as yours. 

Would you be open to getting more contributions here? We could move my content over to yours, and submit your list. What do you think? 

CF: https://github.com/sindresorhus/awesome/pull/708#issuecomment-231539032

**Comment by chbrown** [comment]
Thanks. I wouldn't say 'defunct', but no, I don't spend a whole lot of time keeping it up-to-date :)

It doesn't qualify for sindre's 'awesome' checklist — and now that I think about it, the 'awesome' might be a bit of a misnomer. I didn't intend for it to list just the best annotation software, which is a small field to begin with, plus — even the best is kind of sucky (and yes, I'm insulting a couple of my own projects by saying that).

You can submit a PR if you want to add anything, or, I've just added a license, so feel free to run with it.
